/**
 * 灵枢 AI 工具适配清单
 *
 * 职责：定义 SSoT 真源 → 各 AI 工具产物的映射规则。
 * 修改本文件后执行 `npm run sync` 重新分发。
 *
 * 适配器类型：
 *   - 'directory'：每个 source 在目标目录下生成一个独立文件（适用 Cursor/Trae/Qoder/Antigravity）
 *   - 'file'：所有 source 合并为单一文件（适用 Claude Code 的 CLAUDE.md、Codex 的 AGENTS.md）
 */

/** SSoT 真源文件清单 */
export const sources = [
  { name: 'lingshu-core', path: 'reference/rules/lingshu-core.md' },
  { name: 'ai-behavior', path: 'reference/rules/ai-behavior.md' },
];

/** 各 AI 工具适配器 */
export const adapters = {
  cursor: {
    type: 'directory',
    target: '.cursor/rules/',
    extension: '.mdc',
    frontmatter: {
      'ai-behavior': {
        name: 'ai-behavior',
        description: '灵枢智能体行为准则：Plan 模式存档、真理同步流与原子化交付',
        globs: '**/*',
        trigger: 'always_on',
      },
      'lingshu-core': {
        name: 'lingshu-core',
        description: '灵枢架构核心宪法：脑体解耦、Git 物理隔离与路径映射',
        globs: '**/*',
        trigger: 'always_on',
      },
    },
  },

  trae: {
    type: 'directory',
    target: '.trae/rules/',
    extension: '.md',
  },

  qoder: {
    type: 'directory',
    target: '.qoder/rules/',
    extension: '.md',
  },

  antigravity: {
    type: 'directory',
    target: '.agent/rules/',
    extension: '.md',
  },

  'claude-code': {
    type: 'file',
    target: 'CLAUDE.md',
    header: [
      '<!-- ⚠️ AUTO-GENERATED — DO NOT EDIT -->',
      '<!-- Source: reference/rules/  →  generated by .lingshu/scripts/sync-rules.mjs -->',
      '<!-- 修改请编辑 reference/rules/ 下的真源文件，然后执行 `npm run sync` -->',
      '',
      '# 🌀 灵枢 (LingShu) — Claude Code 项目指令',
      '',
      '> 本文件由灵枢分发脚本自动生成。所有规则的真理来源位于 `reference/rules/`。',
      '',
    ].join('\n'),
    separator: '\n\n---\n\n',
  },

  codex: {
    type: 'file',
    target: 'AGENTS.md',
    header: [
      '<!-- ⚠️ AUTO-GENERATED — DO NOT EDIT -->',
      '<!-- Source: reference/rules/  →  generated by .lingshu/scripts/sync-rules.mjs -->',
      '<!-- 修改请编辑 reference/rules/ 下的真源文件，然后执行 `npm run sync` -->',
      '',
      '# 🌀 灵枢 (LingShu) — AI Agents 项目指令',
      '',
      '> 本文件由灵枢分发脚本自动生成。所有规则的真理来源位于 `reference/rules/`。',
      '',
    ].join('\n'),
    separator: '\n\n---\n\n',
  },
};

/**
 * 团队基线工具：默认入库（产物受 git 追踪，保证克隆即用）
 * 个人偏好工具：默认 ignore（每位开发者本地生成，互不干扰）
 */
export const baseline = ['claude-code', 'codex'];
